# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally, 
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
language: generic


matrix:
  include:
    - os: linux
    - os: osx
      language: generic # python doesn't seem to work on osx images
      if: branch = master AND type != pull_request

env:
  - PYTHON_VERSION="3.6"

before_install:
  # brew-installed geos interferes with cartopy?
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew uninstall --ignore-dependencies geos gdal postgis;
    fi

install:
  # Install conda
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # it might be faster to start from anaconda instead of miniconda
  - travis_wait 20 conda env create --file environment.yml python=$PYTHON_VERSION
  - source activate pyviz
  # dependencies for tests etc
  - pip install flake8
  - conda env export
  - conda list

script:
    - python download_sample_data.py
    # python ./etc/test_notebooks.py lint
    - python ./etc/test_notebooks.py

notifications:
  email: false
